{{- if .Values.operator.enabled -}}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.operator.webhookCertIssuerName }}
spec:
  selfSigned: {}
{{- end -}}
{{- end -}}

