{{- if .Values.operator.enabled -}}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "operator.selfSignedCertIssuerName" . }}
spec:
  selfSigned: {}
{{- end -}}
{{- end -}}

