{{- if .Values.operator.enabled -}}
{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "operator.fullname" . }}
spec:
  dnsNames:
    - {{ include "operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "operator.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "operator.selfSignedCertIssuerName" . }}
  secretName: {{ include "operator.webhookCertSecretName" . }}
{{- end -}}
{{- end -}}
