{{- if .Values.scheduler.enabled -}}
{{- if .Capabilities.APIVersions.Has "cilium.io/v2" -}}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-{{ include "operator.fullname" . }}
spec:
  description: "Allow GPU scheduler pods to access the Kubernetes API server."
  endpointSelector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  egress:
  - toEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "6443"
        protocol: TCP
      - port: "8081"
        protocol: TCP
  ingress:
  - fromEntities:
    - cluster
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      - port: "6443"
        protocol: TCP
      - port: "8000"
        protocol: TCP
      - port: "8081"
        protocol: TCP
{{- end -}}
{{- end -}}
