{{- if .Values.operator.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.metricsReaderRoleName" . }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{- end -}}