{{- if .Values.operator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.webhookServiceName" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "operator.labels" . | nindent 4 }}
{{- end -}}