{{- if .Values.scheduler.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
  name: {{ include "scheduler.fullname" . }}
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      {{- include "scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scheduler.selectorLabels" . | nindent 8 }}
        {{- with .Values.scheduler.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.scheduler.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "scheduler.fullname" . }}
          image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
          args:
            - --config
            - /etc/kubernetes/scheduler_config.yaml
            - --v={{ .Values.scheduler.logLevel }}
            {{- if .Values.scheduler.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10259
              scheme: HTTPS
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.scheduler.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: scheduler-config
              readOnly: true
      hostNetwork: false
      hostPID: false
      serviceAccountName: {{ include "scheduler.fullname" . }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            name: {{ include "scheduler.config.configMapName" .}}
          name: scheduler-config
{{- end -}}