{{- if .Values.gpuPartitioner.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gpuAgent.config.configMapName" . }}
data:
  {{ include "gpuAgent.configFileName" . }}: |-
    apiVersion: config.nos.nebuly.com/v1alpha1
    kind: GpuAgentConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    leaderElection:
      leaderElect: false
    reportConfigIntervalSeconds: {{ .Values.gpuPartitioner.gpuAgent.reportConfigIntervalSeconds}}
{{- end -}}