{{- if .Values.gpuPartitioner.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    control-plane: nos-controller-manager
    {{- include "gpuAgent.labels" . | nindent 4 }}
  name: {{ include "gpuAgent.fullname" . }}
  annotations:
    ignore-check.kube-linter.io/privileged-container: "It needs tor run nvidia mig commands"
    ignore-check.kube-linter.io/privilege-escalation-container: "It needs to run nvidia mig commands"
    ignore-check.kube-linter.io/run-as-non-root: "It needs to run nvidia mig commands"
    ignore-check.kube-linter.io/unset-cpu-requirements: "It needs to run nvidia mig commands"
    container.seccomp.security.alpha.kubernetes.io/kube-rbac-proxy: runtime/default
    container.seccomp.security.alpha.kubernetes.io/{{ include "gpuAgent.fullname" . }}: runtime/default
spec:
  selector:
    matchLabels:
      control-plane: nos-controller-manager
      {{- include "gpuAgent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: nos-controller-manager
        {{- include "gpuAgent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gpuAgent.fullname" . }}
      nodeSelector:
        nos.nebuly.com/gpu-partitioning: mps
      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 20
      {{- if .Values.gpuPartitioner.gpuAgent.runtimeClassName }}
      runtimeClassName: {{ .Values.gpuPartitioner.gpuAgent.runtimeClassName }}
      {{- end }}
      containers:
        - image: "{{ .Values.gpuPartitioner.gpuAgent.image.repository }}:{{ .Values.gpuPartitioner.gpuAgent.image.tag | default .Chart.AppVersion }}"
          name: {{ include "gpuAgent.fullname" . }}
          imagePullPolicy: {{ .Values.gpuPartitioner.gpuAgent.image.pullPolicy }}
          args:
            - --config={{ include "gpuAgent.configFileName" . }}
            {{- if gt (int .Values.gpuPartitioner.gpuAgent.logLevel) 0 }}
            - --zap-log-level={{ .Values.gpuPartitioner.gpuAgent.logLevel }}
            {{ end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.gpuPartitioner.gpuAgent.resources | nindent 12 }}
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /{{ include "gpuAgent.configFileName" . }}
              name: gpu-agent-config
              subPath: {{ include "gpuAgent.configFileName" . }}
            - mountPath: /var/lib/kubelet/pod-resources/kubelet.sock
              name: device-plugin
            - mountPath: /run/nvidia
              mountPropagation: HostToContainer
              name: run-nvidia

        - name: kube-rbac-proxy
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            {{- if gt (int .Values.gpuPartitioner.kubeRbacProxy.logLevel) 0 }}
            - --v={{ .Values.gpuPartitioner.kubeRbacProxy.logLevel }}
            {{ end }}
          image: "{{ .Values.gpuPartitioner.kubeRbacProxy.image.repository }}:{{ .Values.gpuPartitioner.kubeRbacProxy.image.tag }}"
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources: {{- toYaml .Values.gpuPartitioner.kubeRbacProxy.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
          {{- with .Values.gpuPartitioner.gpuAgent.tolerations }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
      volumes:
        - configMap:
            name: {{ include "gpuAgent.config.configMapName" . }}
          name: gpu-agent-config
        - hostPath:
            path: /var/lib/kubelet/pod-resources/kubelet.sock
          name: device-plugin
        - hostPath:
            path: /run/nvidia
            type: Directory
          name: run-nvidia
{{- end -}}