{{- if .Values.gpuPartitioner.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gpuPartitioner.fullname" . }}-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gpuPartitioner.leaderElectionRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gpuPartitioner.fullname" . }}
{{- end -}}