{{- if .Values.gpuPartitioner.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpuAgent.fullname" . }}
  labels:
    {{- include "gpuAgent.labels" . | nindent 4 }}
{{- end -}}