{{- if .Values.gpuPartitioner.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpuPartitioner.fullname" . }}
  labels:
    {{- include "gpuPartitioner.labels" . | nindent 4 }}
{{- end -}}