{{- if .Values.gpuPartitioner.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "migAgent.fullname" . }}
  labels:
    {{- include "migAgent.labels" . | nindent 4 }}
{{- end -}}